language: generic

sudo: required
services:
  - docker
before_install:
#  - openssl aes-256-cbc -K ... # decrypt .enc file command from travis cli
  - curl https://sdk.cloud.google.com | bash > /dev/null; # download and install google cloud sdk
  - source $HOME/google-cloud-sdk/path.bash.inc # load functions from this file
  - gcloud components update kubectl # get the latest kubectl
  - gcloud auth activate-service-account --key-file service-account.json # service-account.json file from GCP, encrypted & installed to travis ci server
  - gcloud config set project <id associated with project>
  - gcloud config set compute/zone <some_zone for cluster> # specify compute zone
  - gcloud container clusters get-credentials <cluster_name> # only deploy to this cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin # referencing environment variables in travis env
  - docker build -t dtrambaud/<some_temp_tag> -f <relative_path_to_dockerFile> <buildContext>

script:
  - docker run dtrambaud<some_temp_tag> npm run test