language: generic

# require sudo priv, docker service to execute build on
sudo: required
services:
  - docker

# build app image w/ dockerfile (dev)
before_install:
  - docker build -t dtrambaud/docker-reactjs -f ./web-applications/reactjs-expressjs/reactjs/Dockerfile.dev ./web-applications/reactjs-expressjs/reactjs/

# run test suite
script:
  - docker run -e CI=true dtrambaud/docker-reactjs npm run test

# deploy (to aws)
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-195465432763"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
