apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false # do not push, given local dev environment
  artifacts: # containers to manage via skaffold
    - image: dtrambaud/multi-client
      context: reactjs
      docker:
        dockerfile: Dockerfile.dev
      sync: # watch for file changes in these extensions
        '**/*.js': .
        '**/*.css': .
        '**/*.html': .
    - image: dtrambaud/multi-server
      context: expressjs
      docker:
        dockerfile: Dockerfile.dev
      sync: # watch for file changes in these extensions
        '**/*.js': .
    - image: dtrambaud/multi-daemon
      context: daemon
      docker:
        dockerfile: Dockerfile.dev
      sync: # watch for file changes in these extensions
        '**/*.js': .
deploy:
  kubectl:
    manifests: # deployments here are automatically cleaned up if SIGKILL issued
      - k8s/client-deployment.yaml
      - k8s/server-deployment.yaml
      - k8s/daemon-deployment.yaml
      - k8s/server-cluster-ip-service.yaml
      - k8s/client-cluster-ip-service.yaml