# Salient purpose of a docker-compose file is to automate the process of executing individual Docker CLI
# statements. Becomes handy when dealing with more than one service! In a docker-compose environment, the network
# or communication between two or more containers is already in place.

# A version must be specified to signal which version of docker compose to use
version: "3"

# The 'services' tag reports how many containers to create given a certain specification
services:
  # service/container-0 which contains ...
  redis-server: # This is a hostname given to a container, value may be anything
    image: "redis" # States what image to load on the container
  # service/container-1 which contains
  node-app: # A user defined alias/hostname
    restart: on-failure # defines the container restart policy, has the following values: ( "no" | on-failure | always | unless-stopped )
    build: . # tells docker-compose where to find the Dockerfile
    ports: # defines the host <-> container mapping
      - 8080:8080 # host_port:container_port -- in this project, the express server is binding to port 8080 and exposed via port 8080 on the host
